### ISSUE TITLE
SpTC examples are needed.

### ISSUE THREAD

**Issue by xichuang** [pnnl/HiParTI#1]
If I had two coo sparse tensors in memory(not in file), stored with data pointers for the indices and the values.
Would you please provide a c example to do tensor contraction, and to get the indices and data pointers of the result tensor?

**Comment by fruitfly1026** [comment]
Dear Wei,

Thank you for your question. We have not yet put the SpTC into the master
branch. But you could find it in the "Sparta" branch under
"benchmark/ttt.c".

**Comment by xichuang** [comment]
I've already noticed the "Sparta" branch. But all examples read data from files. I want to know how to assign data point to COO tensor directly, and how to get data from it. Thank you for your reply and your outstanding work.

**Comment by xichuang** [comment]
I can manage this by my self. Thank you agian.

**Comment by fruitfly1026** [comment]
Hi Wei,

After reading from files, the COO tensor will be formed. You can use
the "ptiDumpSparseTensor" to dump the tensor in COO format or get data
points directly.
Thanks.
